<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630095017 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant_rembourse NUMERIC(10, 2) NOT NULL, statut VARCHAR(50) NOT NULL, methode_paiement VARCHAR(255) DEFAULT NULL, reference_remboursement VARCHAR(255) DEFAULT NULL, nombre_tentatives INT NOT NULL, date_echec TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif_echec VARCHAR(255) DEFAULT NULL, a_refaire BOOLEAN NOT NULL, a_rembourser BOOLEAN NOT NULL, motif_rejet TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_remboursement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ticket_id INT NOT NULL, ticket_parent_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B2C1458700047D2 ON refund (ticket_id)');
        $this->addSql('CREATE INDEX IDX_5B2C1458E840103A ON refund (ticket_parent_id)');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_commande DATE NOT NULL, id_commande VARCHAR(255) NOT NULL, reference_commande VARCHAR(255) NOT NULL, id_transaction VARCHAR(255) NOT NULL, methode_paiement VARCHAR(50) NOT NULL, identifiant_compte VARCHAR(255) NOT NULL, type_transaction VARCHAR(100) NOT NULL, montant_commande NUMERIC(10, 2) NOT NULL, code_reponse VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, statut VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA3A76ED395 ON ticket (user_id)');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C1458E840103A FOREIGN KEY (ticket_parent_id) REFERENCES ticket (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" DROP is_active');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458700047D2');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C1458E840103A');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3A76ED395');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('ALTER TABLE "user" ADD is_active BOOLEAN DEFAULT true NOT NULL');
    }
}
